### PR TITLE
Home page merge request

### PR DESCRIPTION
**Pull request by Mikearaya**
in this pull request, I have created the home page and completed the required features including:
- support 3 different screen sizes
- re-order blocks on different screen sizes (make top story appear at the top on mobile view)
- navigation bar sticky on mobile devices. (on a large screen it requires Javascript)
- the separated the main section in three and made them responsive on 3 different screen sizes
- added footer

# I kindly request your review so I can merge the branch into `master` :smiley:

### CODE REVIEW

**Comment by sumancrest0001** [comment]
**STATUS: CHANGES REQUIRED
Impressive work @Mikearaya :clap: :clap:** 
You are very close to getting a green signal from our side. Since this is a clone project, we have to make it similar to that of the original page. So, a couple of changes required.

[Required] Please remove errors pointed out by the HTML validator.
[Required] Use as many **bootstrap class** as possible and avoid using **! important** in your CSS file it is not a good practice. :slightly_smiling_face: 
[Required] Please give some bottom margin to your navbar on a large screen and change the layout for the medium screen and small screen. it looks off-color. 
**currently in your project :point_down:** 
Screenshot from 2020-04-15 15-24-29

**it should be :point_down:** 
Screenshot from 2020-04-15 15-24-13

**Comment by sumancrest0001** [comment]
[Required] subscriber and newsletter sections should have the same height on a large screen. 
in your project :point_down: 
Screenshot from 2020-04-15 15-20-00

it should be :point_down: 
Screenshot from 2020-04-15 15-19-29

[Required] also fix the alignment of the Newsweek logo and social media icons at the footer and try to achieve a similar layout on all screen types. 
on the small screen, it looks like this in your project :point_down: 
Screenshot from 2020-04-15 15-43-18

it should be 
Screenshot from 2020-04-15 15-43-10

**Comment by sumancrest0001** [comment]
[Required] On the medium screen subscriber and newsletter section should have two columns but in your project, it's only one. 
in your project :point_down: 
Screenshot from 2020-04-15 15-23-43

it should be like this :point_down: 

Screenshot from 2020-04-15 15-24-00

**Comment by sumancrest0001** [comment]
[Optional] Try to make the similar font size and font-weight for the section heads like **editor's pick, US SPORTS etc.**

Kindly make the above-requested changes and submit the project for another review.

**Have question? DM me on Slack Suman Shrestha**
**Happy coding**

**Comment by Mikearaya** [comment]
hi @sumancrest0001 
Thank you for your quick and insightful full response, unfortunately, some mistakes were made even though I tried to do everything perfectly and I appreciate for pointing them out to me. 

I have fixed all the required and optional adjustment stated on the review such as:
- removing warnings pointed out by the HTML validator.
- replaced CSS properties that can be replaced with a bootstrap
- removed unnecessary `!important` statement from CSS (i have left few which i used intentionally to override bootstrap properties. that is recommended in best practices)
-  gave bottom margin to your navbar on a large screen and change the layout for the medium screen and small screen
- made subscription and newsletter section equal height
- fixed alignment of bottom social links and logo on the small screen
- gave uniform `font-size` and `font-family` for section headers

**Comment by mikenath223** [comment]
### Pull request currently under review by Michgolden Ukeje (TSE).
Kindly exercise patience 👋

**Review by mikenath223 — CHANGES_REQUESTED** [review]
### Hi @Mikearaya  👋

You've done really well on this project.

Nice job so far 👌

However, kindly fix these issues before we proceed:

- [ ] Required - Please fix the bottom scrollbar issue, it appears on all screen sizes and doesn't show responsiveness. Kindly fix this. [Screencast]👇
ice_screenshot_20200415-135748

- [ ] Required - Also consider amending the height of the navbar on screen sizes of 1300px and above. [Screenshot]👇
ice_screenshot_20200415-140101

- [ ] Required - In addition please remove the inline comments that exist on your HTML code, if you want to refer to a previous version of your code please use git history.

Kindly fix these issues and request another review👍
Feel free to contact me on slack(michgolden) if you need further clarification.

HAPPY CODING👨‍💻

**Comment by Mikearaya** [comment]
hi @mikenath223 
thank you for your quick response. I have fixed all the issues outline in your review.

- removed HTML comments
- decrease hight of the navbar on viewport >= 1200
- removed scroll bar

**Comment by thsvr** [comment]
### **STATUS: CHANGES REQUESTED** :muscle: 

Hi @Mikearaya :smile: 

**You have been doing a great job and you are almost there** :+1: There is just one thing that you need to fix, so can you read the line below and do the change before the next code review?

:bug: As mentioned by Mike(TSE): _''Required - Please fix the bottom scrollbar issue, it appears on all screen sizes and doesn't show responsiveness. Kindly fix this.''_ It is important to fix it to get the project approved. Can you please fix the orange x-scroll bar? 


x-scroll

 **You got the main idea of the name of the features branches** :trophy: 


If you have any questions, don't hesitate to contact me through slack [@thaís Vieira Azevedo](url)

### **Happy coding and good luck on the next review** :computer: 

_Project reviewed by Thaís Vieira (TSE)_

**Comment by Mikearaya** [comment]
### link to demo might not have updated after making change use this [link](https://rawcdn.githack.com/Mikearaya/newsweek-clone/0f302cc280198edbfb5d05f8c99ffebe0ae6c936/index.html) instead to get the latest view. 
thank you.

**Review by addod19 — CHANGES_REQUESTED** [review]
## Status: Require changes ♻️ 🚥 

Hi @Mikearaya, your project looks great 👍 You did a great job working on the changes requested by the previous TSE's 🙂 Let us make it even better by working on the comments below:

- ```Nav in medium-size```, kindly work on the subscribe button. Let it look like the original since our main focus is cloning the site
- Let us improve the newsletter section. Kindly compare the following images and make the changes
```Our version```
nb1
```Original```
nb
```In medium screen-size```, the newsletter and subscribe takes the full width. Let us compare ours to the original
```Our version```
nb3
```Original```
nb2
```Our version```
nb4
```Original```
nb5
Let us position the social icons as the original
```Nav in small screen-size```, our subscribe button breaks on a small screen, kindly fix it

[OPTIONAL]
Since our main focus is using bootstrap classes everywhere, let us reduce the size of the CSS file and use more of the bootstrap classes. For example, we could use ```mt-*``` instead of ```margin-top: *``` etc

Kindly make these changes and submit another code review 😄 
_Happy coding_ 👨‍💻 
Daniel Larbi Addo on slack

**Comment by Mikearaya** [comment]
hi @addod19 
thank you for your timely review and observing things I've missed it's always great to have another eye on your code:smile: 
I have fixed all the required and optional changes listed as much as I can. (didn't want to change some margin values I used for the critical area with bootstrap )  :smile: .

mainly this the fixes I made.
- tweaked subscription and signup button to look more like the original page
- adjusted breakpoint of newsletter & subscription section
- fixed breaking point of bottom logo section / social linked and adjusted few margins
- changed changes CSS values with bootstrap when possible

**Review by addod19 — APPROVED** [review]
## Status: Approved 🏆 🎈 

Hi @Mikearaya, congratulations on fixing all the required changes 👍 your project now meets all the minimum requirements. I hereby approve the project 😄 

Go ahead and merge to master and submit the project completion form 
_Happy coding_ 👨‍💻 
Good luck with your next projects
Daniel Larbi Addo on slack

**Pull request merged**
